name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ASCOF FORTE.png
    - assets/bioflu.jpg
    - assets/neozep.png
    - assets/Cetirizine.jpg
    - assets/claritin.jpg
    - assets/benadryl.png
    - assets/ambroxol.jpg
    - assets/Solmux.png
    - assets/sinecod.jpg
    - assets/X (2).jpg
    - assets/pharmacycounter.jpeg
    - assets/Counter.jpeg
    - assets/pharmacytablep2.jpeg
    - assets/counterr.png